apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qdrant
  name: qdrant
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: qdrant
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qdrant
    spec:
      containers:
      - image: qdrant/qdrant:v1.13.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: 6333
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: qdrant
        ports:
        - containerPort: 6333
          name: http
          protocol: TCP
        - containerPort: 6334
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 6333
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "14"
            memory: 56Gi
          requests:
            cpu: "8"
            memory: 32Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        app: qdrant
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: qdrant-data
        persistentVolumeClaim:
          claimName: qdrant-storage