{{- if and .Values.autoindexer.enabled .Values.autoindexer.docsIndexer.enabled }}
apiVersion: autoindexer.kaito.sh/v1alpha1
kind: AutoIndexer
metadata:
  name: {{ .Values.autoindexer.docsIndexer.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qdrant-rag.labels" . | nindent 4 }}
    component: docs-autoindexer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "11"  
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  dataSource:
    type: Git
    git:
      repository: {{ .Values.autoindexer.docsIndexer.dataSource.git.repository }}
      branch: {{ .Values.autoindexer.docsIndexer.dataSource.git.branch }}
      paths:
        {{- range .Values.autoindexer.docsIndexer.dataSource.git.paths }}
        - {{ . | quote }}
        {{- end }}
  driftRemediationPolicy:
    strategy: {{ .Values.autoindexer.docsIndexer.driftRemediationPolicy.strategy }}
  indexName: {{ .Values.autoindexer.docsIndexer.indexName }}
  ragEngine: {{ .Values.ragengine.name }}
{{- end }}