{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant-rag.fullname" . }}-qdrant
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qdrant-rag.labels" . | nindent 4 }}
    component: qdrant
spec:
  internalTrafficPolicy: Cluster
  type: {{ .Values.qdrant.service.type }}
  ports:
  - name: http
    port: {{ .Values.qdrant.service.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.qdrant.service.httpPort }}
  - name: grpc
    port: {{ .Values.qdrant.service.grpcPort }}
    protocol: TCP
    targetPort: {{ .Values.qdrant.service.grpcPort }}
  selector:
    {{- include "qdrant-rag.selectorLabels" . | nindent 4 }}
    component: qdrant
  sessionAffinity: None
{{- end }}